name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Schritt 1: Repository klonen
    - name: Check out the repository
      uses: actions/checkout@v3

    # Schritt 2: Python installieren
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Schritt 3: Abhängigkeiten installieren (falls vorhanden)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Schritt 4: Tests mit unittest ausführen
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"

    # Schritt 5: PYTHONPATH setzen
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

